<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="52" started-at="2019-02-28T06:29:05Z" finished-at="2019-02-28T06:29:05Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="52" started-at="2019-02-28T06:29:05Z" finished-at="2019-02-28T06:29:05Z">
      <class name="com.nova1.pageobj.App">
        <test-method status="FAIL" signature="login()[pri:0, instance:com.nova1.pageobj.App@ae45eb6]" name="login" duration-ms="18" started-at="2019-02-28T06:29:05Z" finished-at="2019-02-28T06:29:05Z">
          <exception class="com.codoid.products.exception.FilloException">
            <message>
              <![CDATA[Workbook is not found - //book.xlsx]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.codoid.products.exception.FilloException: Workbook is not found - //book.xlsx
at com.codoid.products.fillo.Fillo.getConnection(Fillo.java:45)
at rediff.rediffloginutils.logsdata(rediffloginutils.java:16)
at com.nova1.pageobj.App.login(App.java:25)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- com.codoid.products.exception.FilloException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
      </class> <!-- com.nova1.pageobj.App -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
